### ISSUE TITLE
Criar no backend uma função para definir o estoque mínimo, sendo preparada para transmitir a informação de mínimo

### ISSUE THREAD

**Issue by BrennoLyrio** [SkyFlyTeam/cloudStock#41]
Rank 8

**Comment by ericloumendes** [comment]
Agora existe no backend, uma tabela que guarda as configurações de sistema, que porta duas variaveis: Estoque Mínimo e alerta Validade. Estoque minimo é um numero inteiro que define a quantidade de estoque que gerara o aviso de que o produto está no minimo. Alerta validade é a quantidade em dias antes no qual ao alerta  de validade será disparado.


### Rotas
```ts
//PUT /configsistema
// Atualiza as configurações de sistema
//Entrada:
/*{
  "Config_estoqueMinimo": 10,
  "Config_avisoValidade": 5
}*/

// GET /configsistema/estoque
// Retorna o número de estoque mínimo

// GET /configsistema/validade
//Retorna o número de dias para o aviso da validade
```
