### ISSUE TITLE
Preço de custo errado, é preço de venda

### ISSUE THREAD

**Issue by ericloumendes** [SkyFlyTeam/cloudStock#55]
Para o cálculo de valor total estamos usando e exibindo preço de custo, o que está incorreto visto que estamos vendendo o produto!

### O que deve ser feito?
1. Alterar a lógica de geração do valor total para utilizar o preço de venda ao invés do preço de custo;
2. Mudar o escrito nas telas para preço de venda ao invés de preço de custo;
3. Exibir as variáveis de preço de venda ao invés das de preço de custo.

**Comment by SarahBatagioti** [comment]
- Conferir na tela de registros
- Conferir na tela de listagem de saídas
