### ISSUE TITLE
Usuário errado

### ISSUE THREAD

**Issue by ericloumendes** [SkyFlyTeam/cloudStock#57]
Alguns registros estão sendo marcados como feitos por um usuário que não realizou aquele registro.

**Comment by gustavomuraoka** [comment]
Não consegui reproduzir o erro sob hipótese alguma, mesmo que tentando diversas ações por determinado tempo, alguma dica ou trigger para induzir o erro e assim arrumá-lo?

**Comment by ericloumendes** [comment]
Tenta criar vários usuários pertencentes ao mesmo cargo e fazer varas entradas ou saídas. O problema estava aparecendo em registros onde uma saida/entrada feita por um usuário X era marcada feita por y.

**Comment by gustavomuraoka** [comment]
Fiz dezenas de entradas e saídas e não obtive o erro em nenhuma delas, suponho que esse erro possa ter vindo em alguma instância de alguma manipulação feita diretamente no mysql workbench que não tenha sido perfeitamente pensada no quesito da consistência dos dados lá atualizados ou que o objeto causador do problema tenha sido resolvido por alguém em outra solução de issue, objeto esse que, causava mais de um problema e agora resolvido para o problema alheio também resolve esse. O que acha? Podemos manter a issue em aberto até que alguém encontre o erro novamente ou então fechamos ela no inicio da sprint que vem, caso não encontremos novamente o erro.

**Comment by ericloumendes** [comment]
Acho que podemos fechá-la sim. O erro deve ter sido ocasionado realmente por erro de versão dentre o back e o front.
