### ISSUE TITLE
Responsividade das telas

### ISSUE THREAD

**Issue by ericloumendes** [SkyFlyTeam/cloudStock#60]
Como apontado na nossa sprint review 2, TODAS AS TELAS devem possuir responsividade.

**Comment by ericloumendes** [comment]
# O que foi feito no commit ca1b3c6 ?
Adicionei parâmetros de responsividade nos css's de Entrada e Saída. Ajustei conforme a wireframe, agora só basta adicionar a sidebar responsiva que estará funcionando!

**Comment by karengoncalves8** [comment]
Ajustei todas as telas da aplicação para serem responsivas para todos os tamanhos de tela, incluindo mobile.
