### ISSUE TITLE
Produzir um MVC e atualizar a documentação

### ISSUE THREAD

**Issue by karengoncalves8** [SkyFlyTeam/cloudStock#75]
Foi solicitado pelo M2 as seguintes alterações em nossa documentação: 
- Fazer uma pasta na main chamada documentação contendo os nossos documentos em pdf, jpg como Product Backlog, Modelo BD e etc
- Produzir o MVC (Model View Controller) do CloudStock e colocar na seção Dor do Cliente no README.MD
- Os links da documentação nos readme.md devem apontar para os documentos na pasta documentação na main
- Criar uma pasta chamada sprint e dentro dela criar uma pasta para cada sprint com suas respectivas documentações 

Modelo a ser seguido: https://github.com/Sync-FATEC/API-2024.2-3SEM

**Comment by BrennoLyrio** [comment]
feito!
