### ISSUE TITLE
Rank 12 - Rotas para produtos mais vendidos, mais comprados, maior rentabilidade e maior custo de compra

### ISSUE THREAD

**Issue by BrennoLyrio** [SkyFlyTeam/cloudStock#85]

**Comment by gui-benedito** [comment]
rota para produtos mais comprados:  /estatisticas/maiorEntrada
rota para produtos mais vendidos:  /estatisticas/maiorSaida
rota para rentabilidade:  /estatisticas/maiorRentabilidade
rota para produtos com mais custos:  /estatisticas/maiorCusto
